// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yhiot.API.Data;

#nullable disable

namespace Yhiot.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230502042623_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Yhiot.API.Models.Agendamento", b =>
                {
                    b.Property<int>("AgendamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExameName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medico")
                        .HasColumnType("TEXT");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.HasKey("AgendamentoId");

                    b.ToTable("agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
